[local]
localhost

[mongodb]
mongodb.subbudevops.online

[redis]
redis.subbudevops.online

[mysql]
mysql.subbudevops.online

[rabbitmq]
rabbitmq.subbudevops.online

[catalogue]
catalogue.subbudevops.online

[user]
user.subbudevops.online

[cart]
cart.subbudevops.online

[shipping]
shipping.subbudevops.online

[payment]
payment.subbudevops.online

[frontend]
frontend.subbudevops.online